### ISSUE TITLE
Cat overlay when muted too big

### ISSUE THREAD

**Issue by bitboxer** [Chatmosphere/chatmosphere-app#23]
If i mute myself i still want to be able to see my face. I get really anxious when i don't see what others see of myself in a video call situation. The cat overlay that shows that i am muted is sadly way too big and i see nothing of myself.

**Comment by dkgrieshammer** [comment]
Thx for your input. This is related to an insight we had in user-testing sessions that people spoke while muted and told us that in every other call-system folks permanently speak while muted too. 
Since we ourselves also suffer by this we made it a goal to show the users that they are mute so boldly that they never talk while muted again. 

But I got your point - what you think about we change background to some crazy color instead? Ideas welcome :)

**Comment by bitboxer** [comment]
What about changing the border of the bubble between red for muted or green for unmuted or something like that?

**Comment by msteudtn** [comment]
I agree with @bitboxer .

In addition, it's also confusing, because you don't know if others see "my" big cat as well.

The red/green border doesn't work for color-blind people. Instead I'd like to suggest

- a semi-transparent overlay (e.g. 50%) and/or
- a smaller overlay that takes only 1/3 of the video.
