### ISSUE TITLE
Session in app. chatmosphere did not work

### ISSUE THREAD

**Issue by EnidKapelsen** [Chatmosphere/chatmosphere-app#92]
With the tool-test last week and Zwischengespräch this week, Chatmosphere did not work. Got same feedback also from other people. 

Also, a dependency: I wanted to invite to the Community Call Next week. Can I invite to app.chatmosphere at all?

**Comment by dkgrieshammer** [comment]
Server Ram was on limit since apparently jitsi uses around 6 gb (3gb for jvb & 3 for jicofo); also java seems to be not very smart in garbage collection so the machine would run out of mem after a while even no conferences are held. 
upped our memory but maybe we should also switch to ngnix instead of apache. managing two different systems is more work and jitsi team seems to favor ngnix in their updates & how-tos;

**Comment by dkgrieshammer** [comment]
Done
